### ISSUE TITLE
Lack of support for ssl

### ISSUE THREAD

**Issue by przemyslaws-iRonin** [janko-m/shrine-url#1]
When url to the remote file is specified by `https` protocol then `EOFError: end of file reached` is raised from the Net::HTTP

**Comment by janko** [comment]
Can you try to come up with a self-contained example that reproduces the problem, or at least the URL for which you're getting this exception and the backtrace of the exception?

**Comment by przemyslaws-iRonin** [comment]
Problematic url is `https://kbob.github.io/images/sample-3.jpg`. 

After enabling ssl in `#request` method everything works properly
`Net::HTTP.start(uri.host, uri.port, use_ssl: uri.scheme == 'https') do |http|`

**Comment by janko** [comment]
@przemyslaws-iRonin To confirm, this error occurs when `#exists?` or `#delete` storage method is called? Because `#download` and `#open` are using the `Down` gem, which should have correct SSL handling.

**Comment by janko** [comment]
Ok, I've managed to reproduce the issue, and am pushing a fix.

**Comment by przemyslaws-iRonin** [comment]
It was for `#exists?` method
