### ISSUE TITLE
Support for redirects

### ISSUE THREAD

**Issue by lucasm-iRonin** [janko-m/shrine-url#2]
Hey @janko-m ,
Thanks for this gem - it's super useful but I have a one question - is it possible to support redirects? It would especially useful for links from dropbox like: https://www.dropbox.com/s/992urij4brdzckd/test_pdf.pdf?dl=1

Unfortunately those links redirect to single use URL so basically every call to `exists?`, `download`, etc. would require to generate a new link by following its redirect. I think it needs to remember how many redirect it should perform for download - otherwise it can invalidate the link by checking the response code, i.e.:

https://www.dropbox.com/s/992urij4brdzckd/test_pdf.pdf?dl=1 -> redirects to A

if you made a request to A (i.e. to check for additional redirect), you invalidate the A link so you can not use it to download the file.

**Comment by janko** [comment]
@lucasm-iRonin `Shrine::Storage::Url#download` already automatically follows up to 2 redirects by default. `Shrine::Storage::Url#open` doesn't follow redirects with the default `Down::NetHttp` backend, though it does with `Down::Http` and `Down::Wget`. I will modify `Down::NetHttp#open` to follow redirects.

`Shrine::Storage::Url#exists?` also obviously doesn't follow redirects, though it's never used automatically by Shrine, it's only used if the user calls `Shrine::UploadedFile#exists?`. I could update `#exists?` to follow redirects, but I think it would even be sufficient to just include `3xx` in "successful response codes".

**Comment by lucasm-iRonin** [comment]
@janko-m thanks for quick reply. I didn't know that following redirects may depend on the backend - we were using the default one which is `Down::NetHTTP`. I can try to switch to other backend to see if it solves the problem.

The case with dropbox links is quite specific - redirects are single time use. If we use `refresh_metadata` plugin does Shrine-url will be able to handle that? First download will be necessary to get the file's metadata and then another one will actually download the file - those 2 requests will need to generate a fresh link from the original dropbox link by following the redirect one more time.

**Comment by janko** [comment]
@lucasm-iRonin Shrine-url will make every request to the original URL (which will redirect to the destination URL), so the destination URL will not be reused.

**Comment by lcmen** [comment]
@janko-m that's great! I will try to switch the backend after the Christmas and let you know if it solves the problem for us.

Thanks again for your excellent support!

**Comment by janko** [comment]
I updated `Shrine::Storage::Url#exists?`and `Down::NetHttp#open` to follow redirects (so switching to `Down::Http` shouldn't be needed). I released shrine-url 1.0.2 and down 4.2.0 with these changes.

**Comment by lucasm-iRonin** [comment]
@janko-m I've just checked it and it works fine. Thanks again!
