### ISSUE TITLE
Proper way to assign multiple versions?

### ISSUE THREAD

**Issue by jcbpl** [janko-m/shrine-url#3]
Per the README's note that "Another advantage is that you can assign multiple remote URLs as multiple versions," is there a recommended way to do that that won't trigger the deprecation warning in `assign_cached` in the versions plugin? 

https://github.com/shrinerb/shrine/blob/1f11094ac9e4966e86d6ca22b5af2b9161de272c/lib/shrine/plugins/versions.rb#L291

**Comment by janko** [comment]
Thanks for reporting this. Yeah, I was going back and forth with this in my mind, but I think I finally decided that the `versions` plugin will support assigning versions, even though it could theoretically be abused. I will push a change shortly to remove the deprecation warning.

We soon plan to add a new `derivates` plugin to Shrine, which will be an improved reimplementation of the `versions` plugin, and which will among other things allow whitelisting assigned versions.

**Comment by jcbpl** [comment]
Thanks, @janko-m!
