### ISSUE TITLE
breaks on long filenames

### ISSUE THREAD

**Issue by jrochkind** [janko-m/shrine-url#4]
i'm trying to use shrine-url with a signed S3 URL. Which is a pretty convenient usecase, importing from S3 (And I def want to do it in backgrounding, thus shrine-url). 

However, it fails on too-long URLs, and signed S3 URLs are quite long (with query params). 

The stack trace doesn't even involve shrine-url, I think it's maybe failing before it even gets to calling shrine url.  Based on trying to make a filename based on `id`, which is the long URL. 

```
Error performing Kithe::AssetPromoteJob (Job ID: 0979ac75-3611-4e99-a63a-be6f5db54957) from Async(default) in 5.67ms: Errno::ENAMETOOLONG (File name too long @ rb_sysopen - /Users/jrochkind/code/scihist_digicoll/tmp/shrine_storage_testing/store/cc65f8b0ebe79f859195410a8a71b025.tif?x-amz-algorithm=aws4-hmac-sha256&x-amz-credential=akiajorcl6txivhsdrhq%2f20181119%2fus-east-1%2fs3%2faws4_request&x-amz-date=20181119t182037z&x-amz-expires=14400&x-amz-signedheaders=host&x-amz-signature=fakefake45db944222adfadfadfadf7d20eacce3e6d062979f993db0ffa1e6e):
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine/storage/file_system.rb:129:in `initialize'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine/storage/file_system.rb:129:in `copy_stream'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine/storage/file_system.rb:129:in `upload'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine.rb:348:in `copy'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine.rb:337:in `put'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine.rb:321:in `_store'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine.rb:248:in `store'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine/plugins/rack_file.rb:72:in `store'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine.rb:226:in `upload'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine/plugins/rack_file.rb:66:in `upload'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine.rb:658:in `store!'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine.rb:588:in `promote'
/Users/jrochkind/.gem/ruby/2.5.3/gems/shrine-2.13.0/lib/shrine/plugins/backgrounding.rb:152:in `promote'
```

I would try to add a failing test... but I notice now shrine-url doesn't even have any tests, so not sure where to add it. Also no idea how to fix this, since it happens before it even gets to shrine-url. I guess it would have to be fixed in shrine itself, to not try to make local files based on id... but it's not expecting id to be super-long like this, the way shrine-url uses it. I wonder if the whole design of shrine-url should be rethought?

Or wait, maybe it looks like the part of shrine that's extracting the filename suffix (to preserve it as it gets promoted), needs to be smart enough to ignore query parameter at the end, in order to be compatible with shrine-url? That might be it?

If you give me feedback and advice, I can try to send some PRs!

**Comment by jrochkind** [comment]
In my own app, I already had a custom plugin for generate_location, and a custom shrine-url storage hardcoded at `remote_url` so I added to my custom generate location:

          basename = super
          if context["storage"] == :remote_url
            basename = URI.parse(basename).path
          end

**Comment by jrochkind** [comment]
Yeah, so the long filename is just a symptom, really the problem is that when used with shrine-url, the query params are making their way into the `id` (and thus subsequent storage path), when they shoudln't be. 

I worked around in my custom code with a custom generate_location override that includes this (among other things)

```ruby

        basename = super
          if io.respond_to?(:storage) && io.storage.is_a?(Shrine::Storage::Url)
            basename = URI.parse(basename).path
          end
```

I am not quite sure what to fix how in shrine itself though, more cleanly.

**Comment by janko** [comment]
> I would try to add a failing test... but I notice now shrine-url doesn't even have any tests, so not sure where to add it.

The tests are here: https://github.com/shrinerb/shrine-url/blob/master/test/url_test.rb 😉 

> Or wait, maybe it looks like the part of shrine that's extracting the filename suffix (to preserve it as it gets promoted), needs to be smart enough to ignore query parameter at the end, in order to be compatible with shrine-url? That might be it?

Yeah, good catch, that seems to be it:

```rb
[1] pry(main)> File.extname("filename.tif?x-amz-algorithm=aws4-hmac-sha256&x-amz-credential=akiajorcl6txivhsdrhq%2f20181119%2fus-east-1%2fs3%2faws4_request&x-amz-date=20181119t182037z&x-amz-expires=14400&x-amz-signedheaders=host&x-amz-signature=fakefake45db944222adfadfadfadf7d20eacce3e6d062979f993db0ffa1e6e")
=> ".tif?x-amz-algorithm=aws4-hmac-sha256&x-amz-credential=akiajorcl6txivhsdrhq%2f20181119%2fus-east-1%2fs3%2faws4_request&x-amz-date=20181119t182037z&x-amz-expires=14400&x-amz-signedheaders=host&x-amz-signature=fakefake45db944222adfadfadfadf7d20eacce3e6d062979f993db0ffa1e6e"
```

Feel free to send the PR if you can, thanks 😃

**Comment by jrochkind** [comment]
I wonder if a question mark could hypothetically be  a real file suffix. This gets weirdly complicated to do reliably, but I'm going to PR something cause I think it needs fixing.
