### ISSUE TITLE
breaks webmock?

### ISSUE THREAD

**Issue by jrochkind** [janko-m/shrine-url#5]
I like using [WebMock](https://github.com/bblimke/webmock) in my tests. 

When trying to write my own test against a shrine uploader using shrine-url, and using WebMock to mock out the HTTP request that shrine-url would be doing...

I get a mysterious error. I haven't yet been able to isolate this error into something that only uses `down` and not `shrine-url`, is why I'm reporting it here. It's really quite mysterious and I'm not sure what's going on, when I try to isolate it into a simple reproduction case, i end up not being able to reproduce. 

Here's the error/stack trace as reported by my rspec, in case it gives you any ideas

```
     Failure/Error: response.connection.close unless @client.persistent?

     NoMethodError:
       undefined method `close' for #<HTTP::Response::Streamer:0x00007ff14aa89380>
       Did you mean?  clone
     # /Users/jrochkind/.gem/ruby/2.5.3/gems/down-4.7.0/lib/down/http.rb:109:in `stream_body'
     # /Users/jrochkind/.gem/ruby/2.5.3/gems/down-4.7.0/lib/down/chunked_io.rb:282:in `each'
     # /Users/jrochkind/.gem/ruby/2.5.3/gems/down-4.7.0/lib/down/chunked_io.rb:282:in `block in chunks_fiber'
```

(Does this also suggest it's using http_rb instead of net_http?  Ah, I see, even though `down` says net-http is the default, shrine-url makes http_rb it's default. Any particular rationale?)

**Comment by jrochkind** [comment]
Trying to get a better stack trace, but having trouble, maybe down's use of fibers/threads is confusing things.

**Comment by jrochkind** [comment]
Appears to be unique to the http_rb backend. If I switch my storage to

     Shrine::Storage::Url.new(downloader: Down::NetHttp.new)

WebMock works fine. 

But I'd rather not switch the downloader from default for no reason but to get WebMock to work; although to make the decision of whether to do so, it would be useful to know why shrine-url chooses httprb as a default, when down has net-http as a default.

**Comment by janko** [comment]
Yeah, the WebMock monkey patches for HTTP.rb still appears to be broken with later versions (https://github.com/httprb/http/issues/212).

The main reason I switched `shrine-url` to HTTP.rb backend _for the user_ is because HTTP.rb has lower memory usage, which is beneficial when uploading large files. Also, when you configure HTTP.rb with a timeout, that's the actual timeout you get (`Net::HTTP` will retry the request once automatically).

The reason _for me_ was that I didn't want to deal with `Net::HTTP` anymore. It's ugly externally, it's ugly internally, and I hate it. And I think that HTTP.rb is a great library, so I think it's a better choice. But if you want to use the `Net::HTTP` backend because of its WebMock support, and you run into issues, I'll still help you out 😃

`Net::HTTP` will probably stay the default backend for `Down`, just because I don't want to force users to install more gems (because in that case I'd need to add `http` as a runtime dependency). Not really a great reason, but I'm trying to strike a balance.

**Comment by janko** [comment]
Note that this particular WebMock error is supposed to be fixed, I remembered now that I've made a patch myself https://github.com/bblimke/webmock/commit/d6a7370d555ce4778fb26ced915920cb59e42305 😄

**Comment by jrochkind** [comment]
Hmm. That commit is in webmock, odd it's not fixed.  I haven't actually been able to reproduce the problem even with just `down` -- I can only reproduce with shrine-url, I can't figure out what shrine-url is doing to trigger the problem. But that commit and test give me a little bit of orientation, thanks.  Any more orientation welcome!

I think shrine-url ends up using http_rb in an uncommon way, so other people aren't running into the bug in webmock, if that's what it is. 

I'd really like to use http_rb, but testing my app reasonably without webmock is challenging. Hmm.

**Comment by jrochkind** [comment]
That fix and test are still in latest version of webmock... so it must be something else?  I will try to investigate a bit more. 

I'm confused about why I can't get any more of a stack trace than those three lines, to see exactly what shrine-url is doing, to be able to write an isolated reproduction of the problem.  I guess it's got something to do with fibers, which shrine-url uses (?), that limits my backtrace?  

If you had any hints for where in the code actually calls things, prior to the stack trace I'm able to get, that would also be helpful.

**Comment by janko** [comment]
That's weird, shrine-url is using Down in the simplest way. Do you think you could come up with self-contained example that reproduces the error? Something like

```rb
require "shrine/storage/url"
require "webmock"

storage = Shrine::Storage::Url.new

storage.download(some_url)
# or
storage.open(some_url).read
```

**Comment by jrochkind** [comment]
Aha!  I was accidentally using WebMock 2.0, before your included fix.  Everything is good with Webmock 3.0. 

Not sure why I was having trouble reproducing, but no longer necessary to find out. 

Sorry for the diversion, thanks for posting the commit that fixed, that led me to figure out why the fix wasn't in my app. Sorry thanks!
