### ISSUE TITLE
Q: Should there be an option to whitelist certain urls/hostnames?

### ISSUE THREAD

**Issue by jrochkind** [janko-m/shrine-url#6]
To avoid user-submitted data being able to download from any arbitrary url?

**Comment by janko** [comment]
Yeah, that would be useful.

For example, when using [shrine-tus](https://github.com/shrinerb/shrine-tus) you'll almost certainly want to allow only URLs from the tus server that you're using. So if support for host whitelisting gets added here, shrine-tus will benefit from that as well.

**Comment by janko** [comment]
I thought about this again, I think whitelisting functionality belongs outside of `shrine-url`. Since it's possible to validate the URL before assigning it as the attachment, there is no need to provide additional validation mechanism inside `shrine-url`.
